config/routes.rb
Rails.application.routes.draw do

  get 'follows/following'

  get 'follows/followers'

  # Routes for static_pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/reload', to: 'static_pages#reload'

  # Routes for users
  resources 'users'
  get '/signup', to: 'users#new'

  # Routes for sessions
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for account_managements
  get '/account_activation', to: 'account_managements#activation_create'
  get '/password_reset', to: 'account_managements#reset_new'
  post '/password_reset', to: 'account_managements#reset_create'
  get '/password_reset_confirmation', to: 'account_managements#reset_edit'
  patch '/password_reset_confirmation', to: 'account_managements#reset_update'

  # Routes for tweets
  resources 'tweets'

  # Routes for follows
  get '/following/:id', to: 'follows#following', as: :following
  get '/followers/:id', to: 'follows#followers', as: :followers
  resources 'follows', only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div id="error-alert">
      <p>Founded <%= pluralize(object.errors.count, "error") %></p>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follow_list.html.erb
<div id="follow-list">
  <% @follows.each do |follow| %>
    <div class="follow-profile content-box">

      <div class="profile-background">
        <%= image_tag('about_bg.jpg') %>
      </div>
      <div class="profile-information">
        <div class="profile-image">
          <%= image_tag('home_bg_2.jpg') %>
        </div>
        <div id="follow-<%= follow.id %>" class="profile-follow">
          <!-- This rendering method below the comment should give a definition of
          the local variable which names follow unless instance variable. -->
          <%= render 'follows/follow_users', follow: follow %>
        </div>
      </div>
      <div class="profile-description">
        <ul>
          <li><%= link_to follow.name_omit, user_path(follow) %></li>
          <li><p><%= follow.name %></p></li>
        </ul>
        <p>Sample and samples</p>
      </div>

    </div>
  <% end %>
</div>

app/views/shared/_follow_page.html.erb
<%= render 'shared/user_header' %>

<div id="two-columns" class="follow-page">
  <div id="columns-left">
    <%= render 'shared/user_profile' %>

    <%= render 'shared/trends' %>
  </div>

  <div id="columns-right">

    <%= render 'shared/follow_list' %>

  </div>



</div>

app/views/shared/_index_page.html.erb
<div id="two-columns">
  <div id="columns-left">
    <%= render 'shared/index_profile' %>

    <%= render 'shared/trends' %>
  </div>

  <div id="columns-right">

      <div id="columns-right-left">
        <div class="content-box">
          <%= render 'tweets/new' %>

          <div id="tweet-line">
            <%= render 'shared/tweet_list' %>
          </div>

        </div>

      </div>

      <div id="columns-right-right">
        <%= render 'shared/trends' %>
      </div>

    </div>



</div>

app/views/shared/_index_profile.html.erb
<div id="index-profile" class="content-box">

  <div class="profile-background">
    <%= image_tag('about_bg.jpg') %>
  </div>

  <div class="profile-information">
    <div class="information-thumbnail">
      <%= image_tag('home_bg_2.jpg') %>
    </div>
    <ul class="information-name">
      <li><%= link_to @user.name_omit, user_path(@user) %></li>
      <li>@<%= @user.name %></li>
    </ul>
  </div>

  <ul class="profile-list">
    <li>Tweets<br><%= link_to @user.tweets.count, user_path(@user) %></li>
    <li>Following<br><%= link_to @user.following.count, following_path(@user) %></li>
    <li>Followers<br><%= link_to @user.followers.count, followers_path(@user) %></li>
  </ul>
  
</div>

app/views/shared/_trends.html.erb
<div class="content-box trends">
  <p>This contains will be filled with reccomended users to follow.</p>
</div>

app/views/shared/_tweet_list.html.erb
<div id="tweet-list">
  <% @tweets.each do |tweet| %>
    <div id="<%= tweet.user.id %>-<%= tweet.id %>" class="list-tweet">
      <%= image_tag('home_bg_2.jpg', class: 'tweet-thumbnail') %>

      <div class="tweet-info">
        <ul class="info-title">
          <li><%= link_to tweet.user.name_omit, user_path(tweet.user) %></li>
          <li>@<%= tweet.user.name %></li>
          <li><%= tweet.tweeted_at %></li>
        </ul>
        <p class="info-content"><%= tweet.content %></p>
        <ul class="info-icons">
          <li><%= fa_icon "reply" %></li>
          <li><%= fa_icon "retweet" %></li>
          <li><%= fa_icon "star" %></li>
          <% if logged_in? && (log_user.admin? || tweet.user == log_user) %>
            <li><%= link_to fa_icon("remove"), tweet_path(tweet), method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if (session[:forwarding_url] == root_url && @tweets.count < @user.feed.count) ||
    (session[:forwarding_url] == user_url(@user) && @tweets.count < @user.tweets.count) %>
    <div id="tweet-reload">
      <%= link_to "Reload previous tweets", reload_path(id: @user, count: @tweets.count), remote: true %>
    </div>
  <% end %>
</div>

app/views/shared/_user_header.html.erb
<%= image_tag('user_header_bg.jpg', class: 'user-background') %>
<div class="user-thumbnail">
  <%= image_tag('help_bg.jpg') %>
</div>

<div id="user-header" class="global-nav">
  <div id="header-sizing">
    <ul id="header-left">
      <!--
      <li class="left-image">
        <%= image_tag('help_bg.jpg') %>
      </li>
    -->
    </ul>

    <ul id="header-middle" class="header-list">
      <li>
        <%= link_to user_path(@user) do %>
        Tweets<br><span><%= @user.tweets.count %></span>
        <% end %>
      </li>
      <li>
        <%= link_to following_path(@user) do %>
        Following<br><span><%= @user.following.count %></span>
        <% end %>
      </li>
      <li>
        <%= link_to followers_path(@user) do %>
        Followers<br><span><%= @user.followers.count %></span>
        <% end %>
      </li>
    </ul>

    <ul id="header-right">

      <% if logged_in?%>
      <li>
        <i id="user-dropdown" class="dropdown"><%= fa_icon("cog", class: 'fa-lg') %></i>
      </li>
      <script>
        $('#user-dropdown').click(function(){
          $('#user-menu > ul').toggle();
        });
      </script>
      <% end %>


      <% if logged_in? && @user == log_user %>
        <li><%= link_to "Edit profile", edit_user_path(@user), class: 'delete btn btn-info' %></li>
      <% elsif logged_in? && @user != log_user %>
        <li class="follow-user"><%= render 'follows/follow_user' %></li>
      <% end %>

    </ul>
  </div>
  <% if logged_in?%>
  <div id="user-menu" class="drop-menu">
    <ul>
      <li><%= link_to "Tweet to #{@user.name}", '#' %></li>
      <li><%= link_to "Add or remove from lists", '#' %></li>
      <li class="drop-border"></li>
      <li><%= link_to "Mute", '#' %></li>
      <li><%= link_to "Block", '#' %></li>
      <li><%= link_to "Report", '#' %></li>
      <% if logged_in? && (log_user.admin? || @user == log_user) %>
        <li class="drop-border"></li>
        <li><%= link_to "Delete profile", user_path(@user), method: :delete,
         data: { confirm: "Are you sure?" }, class: 'delete' %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

<div id="user-blank"></div>

app/views/shared/_user_page.html.erb
<%= render 'shared/user_header' %>

<div id="two-columns">
  <div id="columns-left">
    <%= render 'shared/user_profile' %>

    <%= render 'shared/trends' %>
  </div>

  <div id="columns-right">

      <div id="columns-right-left">
        <div class="content-box">

          <div id="tweet-line">
            <%= render 'shared/tweet_list' %>
          </div>
        </div>

      </div>

      <div id="columns-right-right">
        <%= render 'shared/trends' %>
      </div>

    </div>



</div>

app/views/shared/_user_profile.html.erb
<div id="user-profile">

  <%= link_to @user.name, user_path(@user), class: 'profile-name' %>
  <p class="profile-id">@<%= @user.name%></p>

  <p class="profile-description">
    A message from Immigration,
    Refugees and Citizenship Canada /
    Un message d'Immigration, Réfugiés
    et Citoyenneté Canada
  </p>

  <ul class="profile-information">
    <li><%= fa_icon("map-marker")%>関東</li>
    <li><%= fa_icon("link")%>kuronekomyu.iinaa.net</li>
    <li><%= fa_icon("calendar-o")%>Joined May 2011</li>
    <li><%= fa_icon("adjust")%>Born on June 11</li>
  </ul>

  <div class="tweet-to btn btn-primary">
    <p><%= fa_icon("edit") %>Tweet to <%= @user.name_omit %></p>
  </div>

</div>