config/routes.rb
Rails.application.routes.draw do

  get 'follows/following'

  get 'follows/followers'

  # Routes for static_pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/reload', to: 'static_pages#reload'

  # Routes for users
  resources 'users'
  get '/signup', to: 'users#new'

  # Routes for sessions
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for account_managements
  get '/account_activation', to: 'account_managements#activation_create'
  get '/password_reset', to: 'account_managements#reset_new'
  post '/password_reset', to: 'account_managements#reset_create'
  get '/password_reset_confirmation', to: 'account_managements#reset_edit'
  patch '/password_reset_confirmation', to: 'account_managements#reset_update'

  # Routes for tweets
  resources 'tweets'

  # Routes for follows
  get '/following/:id', to: 'follows#following', as: :following
  get '/followers/:id', to: 'follows#followers', as: :followers
  resources 'follows', only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/account_managements_controller.rb
class AccountManagementsController < ApplicationController
  before_action :get_user, only: [:reset_edit, :reset_update]
  before_action :valid_user, only: [:reset_edit, :reset_update]
  before_action :reset_expired, only: [:reset_edit, :reset_update]

  def activation_create
    user = User.find_by(email_num: params[:email_num])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.update_attribute(:activated, true)
      user.update_attribute(:activated_at, Time.zone.now)
      log_in(user)
      flash[:success] = "Welcome to Tweeter! Enjoy your time."
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_path
    end
  end

  def reset_new

  end

  def reset_create
    @user = User.find_by(email_num: params[:password_reset][:email_num])
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Sent verify email. Please check it to edit your password."
      redirect_to root_url
    else
      flash.now[:danger] = "Could not verify your account. Please try again."
      render 'reset_new'
    end
  end

  def reset_edit

  end

  def reset_update
    if @user.update_attributes(user_params)
      flash[:success] = "Reset password complete"
      log_in(@user)
      redirect_to root_path
    else
      render 'reset_edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def get_user
      @user = User.find_by(email_num: params[:email_num])
    end

    def valid_user
      unless (@user && @user.activated? && @user.authenticated?(:reset, params[:id]))
        flash[:danger] = "Invalid reset link"
        redirect_to root_url
      end
    end

    def reset_expired
      if @user.reseted_at <= 2.weeks.ago
        flash[:danger] = "Invalid reset link"
        redirect_to root_url
      end
    end

end

app/helpers/account_managements_helper.rb
module AccountManagementsHelper
end

app/views/account_managements/reset_edit.html.erb
<div id="reset-new" class="layout-static">
  <h1>Find your Tweeter account</h1>
  <div class="sign-form">
    <p>Enter your email, or phone number</p><br>
    <%= form_for(@user, url: password_reset_confirmation_path(id: params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email_num, @user.email_num %>

      <%= f.password_field :password, placeholder: "Password" %>

      <%= f.password_field :password_confirmation, placeholder: "Type same password again" %>

      <%= f.submit "Submit", class: 'btn btn-info' %>

    <% end %>
  </div>
</div>

app/views/account_managements/reset_new.html.erb
<div id="reset-new" class="layout-static">
  <h1>Find your Tweeter account</h1>
  <div class="sign-form">
    <p>Enter your email, or phone number</p><br>
    <%= form_for(:password_reset, url: password_reset_path) do |f| %>

      <%= f.text_field :email_num, placeholder: "Email or Phone" %>

      <%= f.submit "Send verification", class: 'btn btn-info'  %>

    <% end %>
  </div>
</div>