config/routes.rb
Rails.application.routes.draw do

  get 'follows/following'

  get 'follows/followers'

  # Routes for static_pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/reload', to: 'static_pages#reload'

  # Routes for users
  resources 'users'
  get '/signup', to: 'users#new'

  # Routes for sessions
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for account_managements
  get '/account_activation', to: 'account_managements#activation_create'
  get '/password_reset', to: 'account_managements#reset_new'
  post '/password_reset', to: 'account_managements#reset_create'
  get '/password_reset_confirmation', to: 'account_managements#reset_edit'
  patch '/password_reset_confirmation', to: 'account_managements#reset_update'

  # Routes for tweets
  resources 'tweets'

  # Routes for follows
  get '/following/:id', to: 'follows#following', as: :following
  get '/followers/:id', to: 'follows#followers', as: :followers
  resources 'follows', only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :logged_in_user
  before_action :url_log, only: [:following, :followers]

  def following
    session.delete(:follow_user_id)
    @user = User.find(params[:id])
    session[:follow_user_id] = @user.id
    @follows = @user.following
  end

  def followers
    session.delete(:follow_user_id)
    @user = User.find(params[:id])
    session[:follow_user_id] = @user.id
    @follows = @user.followers
  end

  def create
    @user = User.find(params[:id])
    log_user.follow(@user)
    #This variable should be an instance to be given the user specification to js template.
    @follow = log_user.following.find(params[:id])
      respond_to do |format|
        format.html { redirect_back_to(root_url) }
        format.js { @user = User.find(session[:follow_user_id]) }
      end
  end

  def destroy
    @user = User.find(params[:id])
    #This variable should be an instance to be given the user specification to js template.

    @follow = log_user.following.find(params[:id])
    log_user.unfollow(@user)
      respond_to do |format|
        format.html { redirect_back_to(root_url) }
        format.js { @user = User.find(session[:follow_user_id]) }
      end

  end

end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow_user.html.erb
<% if log_user.following?(@user) %>
  <%= link_to 'Following', follow_path(@user), method: :delete, class: 'btn btn-unfollow btn-primary', remote: true %>
<% else %>
  <%= link_to 'Follow', follows_path(id: @user), method: :post, class: 'btn btn-follow btn-info', remote: true %>
<% end %>
<script>
  $('.btn-unfollow').hover(function(){
    $(this).html('Unfollow');
    $(this).addClass('btn-danger');
  });
  $('.btn-unfollow').mouseout(function(){
    $(this).html('Following');
    $(this).removeClass('btn-danger');
  });
</script>

app/views/follows/_follow_users.html.erb
<% unless follow == log_user %>
  <% if log_user.following?(follow) %>
    <%= link_to 'Following', follow_path(follow), method: :delete, class: 'btn btn-unfollow btn-primary', remote: true %>
  <% else %>
    <%= link_to 'Follow', follows_path(id: follow), method: :post, class: 'btn btn-follow btn-info', remote: true %>
  <% end %>
<% end %>
<script>
  $('.btn-unfollow').hover(function(){
    $(this).html('Unfollow');
    $(this).addClass('btn-danger');
  });
  $('.btn-unfollow').mouseout(function(){
    $(this).html('Following');
    $(this).removeClass('btn-danger');
  });
</script>

app/views/follows/create.js.erb
$(".profile-list > li:nth-child(2)").html('Following<br><%= link_to @user.following.count, following_path(id: @user) %>');
$(".profile-list > li:nth-child(3)").html('Followers<br><%= link_to @user.followers.count, followers_path(id: @user) %>');
$(".header-list > li:nth-child(2)").html('<%= link_to following_path(@user) do %>Following<br><span><%= @user.following.count %></span><% end %>');
$(".header-list > li:nth-child(3)").html('<%= link_to followers_path(@user) do %>Followers<br><span><%= @user.followers.count %></span><% end %>');
$(".follow-user").html("<%= escape_javascript(render('follows/follow_user')) %>");
$('#follow-<%= @follow.id %>').html("<%= escape_javascript(render('follows/follow_users', follow: @follow)) %>");

app/views/follows/destroy.js.erb
$(".profile-list > li:nth-child(2)").html('Following<br><%= link_to @user.following.count, following_path(id: @user) %>');
$(".profile-list > li:nth-child(3)").html('Followers<br><%= link_to @user.followers.count, followers_path(id: @user) %>');
$(".header-list > li:nth-child(2)").html('<%= link_to following_path(@user) do %>Following<br><span><%= @user.following.count %></span><% end %>');
$(".header-list > li:nth-child(3)").html('<%= link_to followers_path(@user) do %>Followers<br><span><%= @user.followers.count %></span><% end %>');
$(".follow-user").html("<%= escape_javascript(render('follows/follow_user')) %>");
$('#follow-<%= @follow.id %>').html("<%= escape_javascript(render('follows/follow_users', follow: @follow)) %>");

app/views/follows/followers.html.erb
<div id="followers">
  <%= render 'shared/follow_page' %>
</div>

app/views/follows/following.html.erb
<div id="following">
  <%= render 'shared/follow_page' %>
</div>