config/routes.rb
Rails.application.routes.draw do

  get 'follows/following'

  get 'follows/followers'

  # Routes for static_pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  get '/reload', to: 'static_pages#reload'

  # Routes for users
  resources 'users'
  get '/signup', to: 'users#new'

  # Routes for sessions
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for account_managements
  get '/account_activation', to: 'account_managements#activation_create'
  get '/password_reset', to: 'account_managements#reset_new'
  post '/password_reset', to: 'account_managements#reset_create'
  get '/password_reset_confirmation', to: 'account_managements#reset_edit'
  patch '/password_reset_confirmation', to: 'account_managements#reset_update'

  # Routes for tweets
  resources 'tweets'

  # Routes for follows
  get '/following/:id', to: 'follows#following', as: :following
  get '/followers/:id', to: 'follows#followers', as: :followers
  resources 'follows', only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |msg_type, msg| %>
  <div id="flash" class="flash-<%= msg_type %>">
    <p><%= msg %></p>
    <span><%= fa_icon('remove') %></span>
  </div>
  <script>
    $('#flash > span').click(function(){
      $('#flash').hide();
    });
  </script>
<% end %>

app/views/layouts/_header.html.erb
<div id="header-nav" class="global-nav">

  <ul id="pull-left">
    <li class="compact-icon"><%= link_to fa_icon("twitter", class: 'fa-lg'), root_path %></li>
    <li>
      <ul class="non-drop-list">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </li>

  </ul>

  <ul id="pull-right">
    <% if logged_in? %>
      <li class="compact-icon">
        <i id="layout-dropdown" class="dropdown"><%= fa_icon("bars", class: 'fa-lg') %></i>
      </li>
      <li>
        <ul class="non-drop-list">
          <li><%= render 'layouts/search' %></li>
          <li><%= link_to "Profile", user_path(log_user) %></li>
          <li><%= link_to "Setting", edit_user_path(log_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        </ul>
      </li>
      <script>
        $('#layout-dropdown').click(function(){
          $('#layout-menu > ul').toggle();
        });
      </script>

    <% else %>
      <li><%= link_to "Log in", root_path %></li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
<div id="layout-menu" class="drop-menu">
  <ul>
    <li><%= render 'layouts/search' %></li>
    <li class="drop-border"></li>
    <li><%= link_to "Profile", user_path(log_user) %></li>
    <li><%= link_to "Help", help_path %></li>
    <li class="drop-border"></li>
    <li><%= link_to "Setting", edit_user_path(log_user) %></li>
    <li><%= link_to "Log out", logout_path, method: :delete %></li>
  </ul>
</div>
<% end %>

app/views/layouts/_search.html.erb
<div class="search-form">
  <form action="">
    <input type="text">
    <span><%= fa_icon("search") %></span>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweeter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <div id="header">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
    </div>

    <div id="contents">
      <%= yield %>
    </div>

    <div id="footer" class="debug">
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>